apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.testCredentials.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ "admin" | b64enc | quote }}
---
#Secret must be referenced by test pod running in kyma-system, that's why the secret is duplicated
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.testCredentials.secretName }}
  namespace: kyma-system
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ "admin" | b64enc | quote }}