apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.auditlog.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  auditlog-client-id: {{ "client_id" | b64enc | quote }}
  auditlog-client-secret: {{ "client_secret" | b64enc | quote }}
  auditlog-oauth-url: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s/audit-log/v2/oauth/token" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
---
#Secret must be referenced by test pod running in kyma-system, that's why the secret is duplicated
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.auditlog.secretName }}
  namespace: kyma-system
  labels:
    release: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  auditlog-client-id: {{ "client_id" | b64enc | quote }}
  auditlog-client-secret: {{ "client_secret" | b64enc | quote }}
  auditlog-oauth-url: {{ printf "http://compass-external-services-mock.%s.svc.cluster.local:%s/audit-log/v2/oauth/token" .Release.Namespace (.Values.service.port | toString) | b64enc | quote }}
