apiVersion: "testing.kyma-project.io/v1alpha1"
kind: TestDefinition
metadata:
  name: {{ .Values.global.ordAggregator.name }}
  namespace: kyma-system
  labels:
    app: {{ .Chart.Name }}-tests
    app.kubernetes.io/name: {{ .Chart.Name }}-tests
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Chart.Name }}-tests
    spec:
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
          - ip: {{ .Values.global.minikubeIP }}
            hostnames:
              - "{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}"
              - "dex.{{ .Values.global.ingress.domainName }}"
              - "oauth2.{{ .Values.global.ingress.domainName }}"
              - "compass-external-services-mock.compass-system.svc.cluster.local"
      {{ end }}
      containers:
        - name: ord-aggregator-tests
          image: {{ .Values.global.images.containerRegistry.path }}/{{ .Values.global.images.tests.ord_aggregator.dir }}ord-aggregator-tests:{{ .Values.global.images.tests.ord_aggregator.version }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "/ord-aggregator.test -test.v; exit_code=$?; curl -XPOST http://127.0.0.1:15020/quitquitquit; sleep 4; exit $exit_code;"]
          env:
            - name: ORD_SERVICE_URL
              value: "https://{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.ordService.prefix }}"
            - name: ORD_SERVICE_HEALTHZ_URL
              value: "http://compass-ord-service.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.director.port }}/actuator/health"
            - name: DIRECTOR_URL
              value: "https://{{ .Values.global.gateway.tls.host }}.{{ .Values.global.ingress.domainName }}{{ .Values.global.director.prefix }}"
            - name: DIRECTOR_HEALTHZ_URL
              value: "http://compass-director.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.global.director.port }}/healthz"
            - name: EXTERNAL_SERVICES_MOCK_BASE_URL
              value: "http://compass-external-services-mock.{{ .Release.Namespace }}.svc.cluster.local:8080"
            - name: ALL_SCOPES
              value: "{{ .Values.global.director.tests.scopes }}"
            - name: DEFAULT_CHECK_INTERVAL
              value: "{{ .Values.global.ordAggregator.tests.defaultCheckInterval }}"
            - name: DEFAULT_TEST_TIMEOUT
              value: "{{ .Values.global.ordAggregator.tests.defaultTestTimeout }}"
            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: email
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: password
            - name: DEFAULT_TENANT
              value: "{{.Values.global.defaultTenant}}"
            - name: DOMAIN
              value: "{{ .Values.global.ingress.domainName }}"
      restartPolicy: Never
